# Generated by Django 3.1.3 on 2020-11-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='greeting',
            name='club_name',
            field=models.CharField(default='Robotics Club', max_length=500),
        ),
    ]
