# Generated by Django 3.1.3 on 2020-11-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='greeting',
            name='about_department',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='greeting',
            name='department_name',
            field=models.CharField(default='Process Automation Engineering', max_length=250),
        ),
        migrations.AddField(
            model_name='greeting',
            name='students_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='greeting',
            name='teacher_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
