# Generated by Django 3.1.3 on 2020-11-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201109_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greeting',
            name='about_department',
            field=models.TextField(default='Nome'),
        ),
    ]
