# Generated by Django 3.1.3 on 2020-11-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201109_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greeting',
            name='about_department',
            field=models.TextField(default='Nome', null=True),
        ),
    ]
