# Generated by Django 3.1.3 on 2020-11-09 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_greeting_about_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='greeting',
            name='department_name',
        ),
        migrations.RemoveField(
            model_name='greeting',
            name='students_count',
        ),
        migrations.RemoveField(
            model_name='greeting',
            name='teacher_count',
        ),
    ]
