# Generated by Django 3.1.3 on 2020-11-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201109_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='greeting',
            name='teacher_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
