# Generated by Django 3.1.3 on 2020-11-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_greeting_teacher_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='greeting',
            name='students_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
