# Generated by Django 3.1.3 on 2020-11-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_greeting_students_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='greeting',
            name='department_name',
            field=models.CharField(default='Process Automation Engineering', max_length=250),
        ),
    ]
