# Generated by Django 3.1.3 on 2020-11-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_greeting_department_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='greeting',
            name='about_department',
            field=models.TextField(default='This is Department'),
        ),
    ]
