# Generated by Django 3.1.3 on 2020-11-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_research'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('background_img', models.ImageField(upload_to='media')),
                ('main_img', models.ImageField(upload_to='media')),
                ('body', models.TextField(default='Body')),
                ('partner_1_img', models.ImageField(upload_to='media')),
                ('partner_1_link', models.TextField()),
                ('partner_2_img', models.ImageField(upload_to='media')),
                ('partner_2_link', models.TextField()),
                ('partner_3_img', models.ImageField(upload_to='media')),
                ('partner_3_link', models.TextField()),
            ],
        ),
    ]
