# Generated by Django 3.1.3 on 2020-11-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_about_faculty_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('background_img', models.ImageField(upload_to='media')),
                ('goal_1_title', models.CharField(max_length=250)),
                ('goal_1_body', models.TextField()),
                ('goal_1_img', models.ImageField(upload_to='media')),
                ('goal_2_title', models.CharField(max_length=250)),
                ('goal_2_body', models.TextField()),
                ('goal_2_img', models.ImageField(upload_to='media')),
                ('goal_3_title', models.CharField(max_length=250)),
                ('goal_3_body', models.TextField()),
                ('goal_3_img', models.ImageField(upload_to='media')),
            ],
        ),
    ]
