# Generated by Django 3.1.3 on 2020-11-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('background_img', models.ImageField(upload_to='media')),
                ('img', models.ImageField(upload_to='media')),
                ('mail', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=500)),
            ],
        ),
    ]
